// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQBc5ewiiqxjzelWOiBQkatZgW8mnB350',
    appId: '1:376000080785:web:91928b6a7af06822e6c830',
    messagingSenderId: '376000080785',
    projectId: 'app-log1-86a56',
    authDomain: 'app-log1-86a56.firebaseapp.com',
    databaseURL: 'https://app-log1-86a56-default-rtdb.firebaseio.com',
    storageBucket: 'app-log1-86a56.firebasestorage.app',
    measurementId: 'G-6Z9PWY3SQL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1anjWggCuBnN0so5ShPuyex8Nwwcv_6M',
    appId: '1:376000080785:android:68b254b1bbe110b9e6c830',
    messagingSenderId: '376000080785',
    projectId: 'app-log1-86a56',
    databaseURL: 'https://app-log1-86a56-default-rtdb.firebaseio.com',
    storageBucket: 'app-log1-86a56.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDnJP9_GDnBxoB84JpuIkeHUnimymKcLwc',
    appId: '1:376000080785:web:1c613cc0d8e39531e6c830',
    messagingSenderId: '376000080785',
    projectId: 'app-log1-86a56',
    authDomain: 'app-log1-86a56.firebaseapp.com',
    databaseURL: 'https://app-log1-86a56-default-rtdb.firebaseio.com',
    storageBucket: 'app-log1-86a56.firebasestorage.app',
    measurementId: 'G-PFQ8B1RPCT',
  );
}
